name: Build and create resume
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup latex
        run: |
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install texlive-latex-extra
          sudo apt-get install texlive-xetex
      - name: Compile latex file
        run: |
          xelatex resume.tex
      - uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf


          